### ISSUE TITLE
Definition of a perfectoid space

### ISSUE THREAD

**Issue by kbuzzard** [kbuzzard/lean-perfectoid-spaces#3]
# NB 15th Oct 2018 This issue is now out of date

The main problems left have been broken down into smaller issues (2 to 5).

### Perfectoid spaces

A `perfectoid_space` is an `adic_space` with some properties, and the main work involved in formalising the definition of a perfectoid space will be formalising adic spaces. Indeed, modulo adic spaces, the definition of a perfectoid space is basically already in the repository, modulo some basic definitions in the theory of topological rings (bounded subset, power-bounded elements) which we'll have to do for adic spaces anyway. One could imagine a basic `topological_ring.lean` file containing definitions like this, and it would probably not be a hard job to reduce the definition of perfectoid space to the definition of adic space.

### Adic spaces

My proposal for formalizing `adic_space`, the definition of an adic space, is [Torsten Wedhorn's notes](https://www2.math.uni-paderborn.de/fileadmin/Mathematik/People/wedhorn/Lehre/AdicSpaces.pdf). The definition of an adic space is on page 80 of these notes. Note the warning at the beginning, but note also that I have read the definition given in these notes in full and I believe it's fine. In fact, formalizing the definition of an adic space might in some sense be a way of verifying that the notes are fine.

Let me give more details of what needs to be done. Page numbers are all for Wedhorn's notes.

1) An adic space (definition 8.21, p80) is something which is covered by affinoid adic spaces, so one needs to define affinoid adic spaces. Indeed, given the definition of an affinoid adic space it should be relatively easy to formalise the definition of adic space.

2) An affinoid adic space (definition 8.20, p80) -- this is where the meat is. One attaches an affinoid preadic space to a Huber pair (the old name for a Huber pair is an "affinoid ring"); an affinoid preadic space is a topological space with a presheaf of topological rings and some extra structure, and an affinoid preadic space is an affinoid adic space if this presheaf is a sheaf. I define presheaves and sheaves in my [schemes repository](https://github.com/kbuzzard/lean-stacks-project/blob/master/src/tag006T.lean) but I am older and wiser now, and have a clearer idea about how this should be done. I only needed presheaves of rings, not topological rings, but this should be a relatively straightforward extension. One could imagine developing a general theory of presheaves (of types and of topological rings) and of sheaves, however I am unclear about whether one should embark upon presheaves taking values in an arbitrary category at this point, because there is still not much category theory in mathlib (although this will soon change). This theory is just a general part of the geometer's toolkit and is independent of the theory of adic spaces.

3) A Huber pair (called "affinoid ring" in Wedhorn) is defined in definition 7.14(2), page 60. It is a pair consisting of a Huber ring (called "f-adic ring" in Wedhorn, and I won't be the only person pleased to see the back of this notation) and a "ring of integral elements" (definition 7.14(1)). These definitions will be a good test of Lean's type class system and I hoping that they will be relatively straightforward to implement but they involve working with topological rings. In fact it would not be unreasonable to target Huber rings and Huber pairs fairly early on in the formalization process -- we will be working a lot with topological rings and this will just involve formalising some basic definitions in the theory like the topology generated by an ideal of a commutative ring, the notion of a bounded subset of a topological ring and so on.

4) The main work involved in formalising adic spaces is the `Spa` function, which is definition 7.23 on p62. This function eats a Huber pair and spits out an object of the category called $\mathcal{V}^pre$ on p76 of Wedhorn. Explicitly, it spits out a topological space, a presheaf of rings on this space, and also an equivalence class of valuations on the stalks. The topological space is also a space of equivalence classes of valuations.

5) Valuations have basically already been done (by Kenny Lau) and are in the repo, in `src/valuations.lean` at the time of writing, although this might change. One needs to define the topology on the appropriate space of valuations (and prove that it is a topology). The main work here is defining the topology on an auxiliary object $Cont(A)$, which inherits its topology from another auxiliary object $Spv(A)$, whose topology is defined on p23 (definition 4.1).

6) I envisage the hardest part of the formalisation as being the definition of the presheaf on Spa(A). To define it on rational subsets (definition 7.29, p62) one needs a theory of localization (which we have) and a theory of completion (which we don't have). Once we have these, the definition is equation 8.21 on p75. In addition to this, one needs to extend the presheaf to all open subsets, which is a projective limit procedure described just after. Now checking the presheaf axioms will be some work, but it hopefully won't be too hard.

**Comment by kbuzzard** [comment]
I guess a natural place to start with all this would be with the definition of a Huber Pair, so let me go through all of the things one would need for this. One needs the definition of a bounded subset of a topological ring (important note: all rings are commutative with 1 and all ring homs send 1 to 1), a power-bounded element of a topological ring, the notion of a subring of a ring, and what it means for a subring to be integrally closed in the bigger ring, and the J-adic topology on a ring, where J is an ideal of that ring.

**Comment by jcommelin** [comment]
So we don't actually need Tate rings. Is that correct?

**Comment by kbuzzard** [comment]
Well I guess a perfectoid ring is a Tate ring + ...

**Comment by kbuzzard** [comment]
OK so here's an update. I've merged Patrick's and Johan's commits. I defined Spv(A) in `valuation_spectrum.lean` as a quotient, but note that the quotient lives in Type 1 if A lives in Type; I defined another version in `zfc_valuation_spectrum` which lives in `Type` following an idea of Mario; I don't know which one will be easier to work with. There's a bijection from one to the other with a noncomputable inverse.

My main aim at the minute is to define the topological space Spa(A) attached to a Huber Pair. I am working on defining Cont(A) (definition 7.7 of Wedhorn); it is slightly delicate because Gamma is not the target group, it's the group generated by the image of v. I should be able to sort this all out within the next few days. Then Spa(A) will be easy (Definition 7.23), at least as a topological space. We only need to attach a presheaf of rings to it, not a sheaf (the presheaf is not in general a sheaf in this setting). 

It seems to me that the main difficulty in attaching the presheaf will be the theory of completions of topological groups and rings. We will need some, but probably not all, of Wedhorn 5.32 and 5.36. Then we should be well on the way.

Maybe I should say explicitly some things which we definitely will need. We'll need the completion A<T/s> of A(T/s) using notation on p73 of Wedhorn, but only for A a Huber ring. And for the presheaf property we will need the universal property of A->A<T/s>, which is stated in Wedhorn 5.32 for abelian groups, but I guess we will need that if everything is a ring then the universal map is a ring hom.

**Comment by kbuzzard** [comment]
Closing this issue on the basis that it's now four smaller issues.

https://github.com/kbuzzard/lean-perfectoid-spaces/issues/23
https://github.com/kbuzzard/lean-perfectoid-spaces/issues/24
https://github.com/kbuzzard/lean-perfectoid-spaces/issues/25
https://github.com/kbuzzard/lean-perfectoid-spaces/issues/26
