### ISSUE TITLE
Project does not currently compile

### ISSUE THREAD

**Issue by kbuzzard** [kbuzzard/lean-perfectoid-spaces#30]
Following the cut-n-paste installation instructions on `master` gives a repo which does not complile. We have not updated mathlib for a while, and Patrick and I have between us managed to create two non-rfl instances of a class. 

```bash
/home/buzzard/lean-projects/lean-perfectoid-spaces/src/r_o_d_completion.lean:43:2: error: synthesized type class instance is not definitionally equal to expression inferred by typing rules, synthesized
  domain.to_ring (ring_completion (valuation_field (out (v.val))))
inferred
  comm_ring.to_ring (ring_completion (valuation_field (out (v.val))))
```

**Comment by PatrickMassot** [comment]
This description is not accurate, those instances *are* defeq:
```lean
import algebra.field

example (α : Type*) [discrete_field α] :  @domain.to_ring α _  = @comm_ring.to_ring α _  := rfl
```
I really don't know what Lean is doing here. It seems this error message happens at a time where defeq is not good enough. It would be nice to be able to minimize this issue.

**Comment by PatrickMassot** [comment]
This issue is completely outdated.
